# Generated by Django 4.0.3 on 2022-04-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220403_1159'),
        ('catalog', '0024_auto_20210302_0630'),
    ]

    operations = [
    ]
